name: Test
on:
  push:
permissions:
  contents: read
jobs:
  golangci:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Build
        run: cd src && go build -v ./...
      - name: Test
        run: cd src && go test -v ./...
